apiVersion: v1
kind: Service 
metadata:
  name: mywebapp-active-service
  namespace: bluegreen-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mywebapp

---
apiVersion: v1
kind: Service 
metadata:
  name: mywebapp-preview-service
  namespace: bluegreen-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mywebapp