apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-rolling
  namespace: rolling-demo
  labels:
    app: mywebapp-rolling
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mywebapp-rolling
  template:
    metadata:
      labels:
        app: mywebapp-rolling
    spec:
      containers:
        - name: mywebapp
          image: habib0905/mywebapp:v1
          env:
            - name: APP_VERSION
              value: "latest"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
