apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: mywebapp-canary
  namespace: canary-demo
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 10
        - pause: {duration: 30s}
        - setWeight: 50
        - pause : {duration: 60s}
        - setWeight: 100
  selector:
    matchLabels:
      app: mywebapp-canary
  template:
    metadata:
      labels:
        app: mywebapp-canary
        version: "v1"
    spec:
      containers:
        - name: mywebapp
          image: habib0905/mywebapp:latest
          env: 
            - name: APP_VERSION
              value: "latest"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          ports: 
            - containerPort: 8080